mutation subscriptionCancel(
  $accessToken: String!
  $subscription: SubscriptionCancelInput!
) {
  subscriptionCancel(accessToken: $accessToken, subscription: $subscription) {
    subscription {
      id
    }
  }
}
