mutation billingAddressUpdate(
  $accessToken: String!
  $billingInfo: BillingAddressInput!
) {
  billingAddressUpdate(accessToken: $accessToken, billingInfo: $billingInfo) {
    billingInfo {
      stripeCardId
      name
      address1
      address2
      city
      state
      zipcode
      cardBrand
      cardExpMonth
      cardExpYear
      cardLast4
    }
  }
}
