import React, { useContext, useState } from 'react'
import { observer } from 'mobx-react'

import AccountStore from '../../stores/AccountStore'

/**
 * ResetPassword observes AccountStore
 *
 * ResetPassword is only accessable from a user email.
 * The url peram that is required by ResetPassword is generated by shopify and
 * sent with the ResetPassword email.
 *
 */

export const ResetPassword = observer(() => {
  const store = useContext(AccountStore)

  const [error, setError] = useState(false)
  const [password, setPassword] = useState('')
  const [repassword, setRePassword] = useState('')

  const getParameterByName = (name, url) => {
    if (!url) url = window.location
    console.log(name, url)
    /* eslint-disable-next-line */
    name = name.replace(/[\[\]]/g, '\\$&')
    var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
      results = regex.exec(url)
    if (!results) return null
    if (!results[2]) return ''
    return decodeURIComponent(results[2].replace(/\+/g, ' '))
  }

  const resetPassword = async event => {
    event.preventDefault()
    if (repassword === password) {
      var resetUrl = getParameterByName('resetUrl')
      console.log(resetUrl)
      const auth = await store.resetPassword(password, resetUrl)
      if (!auth.errors) {
        window.location.hash = '/login'
      }
    } else {
      setError(true)
      setTimeout(() => {
        setError(false)
      }, 3000)
    }
  }

  return (
    <form
      onSubmit={resetPassword}
      style={{ maxWidth: '400px', margin: 'auto' }}
    >
      {error && (
        <p className="has-text-danger" style={{ marginBottom: '15px' }}>
          Passwords are not the same!
        </p>
      )}
      <div className="field">
        <input
          className="input"
          type="password"
          id="password"
          placeholder="Enter a New Password"
          onChange={event => setPassword(event.target.value)}
        />
      </div>
      <div className="field">
        <input
          className="input"
          type="password"
          id="repassword"
          placeholder="Re Enter your Password"
          onChange={event => setRePassword(event.target.value)}
        />
      </div>
      <input type="submit" value="Reset" className="button is-info" />
    </form>
  )
})
